package com.neu.edu.pojo;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Buyer generated by hbm2java
 */
@Entity
@Table(name = "buyer", catalog = "project")
public class Buyer implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private int buyerID;
	private User user;
	private Set<Property> properties = new HashSet(0);

	public Buyer() {
	}

	public Buyer(User user) {
		this.user = user;
	}

	public Buyer(User user, Set<Property> properties) {
		this.user = user;
		this.properties = properties;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "buyerID", unique = true, nullable = false)
	public Integer getBuyerId() {
		return this.buyerID;
	}

	public void setBuyerId(int buyerId) {
		this.buyerID = buyerId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "userID", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(name = "buyer_property", catalog = "project", joinColumns = {
			@JoinColumn(name = "buyerID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "propertyID", nullable = false, updatable = false) })
	public Set<Property> getProperties() {
		return this.properties;
	}

	public void setProperties(Set<Property> properties) {
		this.properties = properties;
	}

}
