package com.neu.edu.pojo;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Seller generated by hbm2java
 */
@Entity
@Table(name = "seller", catalog = "project")
public class Seller implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private int sellerID;
	private User user;
	
	private Set<Property> properties = new HashSet(0);

	public Seller() {
	}

	public Seller(User user) {
		this.user = user;
	}

	public Seller(User user, Set<Property> properties) {
		this.user = user;
		this.properties = properties;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "sellerID", unique = true, nullable = false)
	public int getSellerID() {
		return this.sellerID;
	}

	public void setSellerID(int sellerID) {
		this.sellerID = sellerID;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "userID", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "seller")
	//@JoinColumn(name="sellerID",nullable=false)
	public Set<Property> getProperties() {
		return this.properties;
	}

	public void setProperties(Set<Property> properties) {
		this.properties = properties;
	}
	public void addProperty(Property property) {
        getProperties().add(property);
    }
}
