package com.neu.edu.pojo;


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "project")
public class User implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private int userId;
	private String userName;
	private String password;
	private String emailID;
	private int phoneNumber;
	private String firstName;
	private String lastName;
	private String role;
	//private Set<Seller> sellers = new HashSet(0);
	//private Set<Buyer> buyers = new HashSet(0);
	private Buyer buyer;
	private Seller seller;
	
	public User() {
	}

	public User(String userName, String password, String emailId, int phoneNumber, String firstName, String lastName) {
		this.userName = userName;
		this.password = password;
		this.emailID = emailId;
		this.phoneNumber = phoneNumber;
		this.firstName = firstName;
		this.lastName = lastName;
	}

	public User(String userName, String password, String emailId, int phoneNumber, String firstName, String lastName,
			Buyer buyer, Seller seller) {
		this.userName = userName;
		this.password = password;
		this.emailID = emailId;
		this.phoneNumber = phoneNumber;
		this.firstName = firstName;
		this.lastName = lastName;
		this.buyer = buyer;
		this.seller = seller;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "userID", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "userName", nullable = false, length = 45)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "emailID", nullable = false, length = 45)
	public String getEmailID() {
		return this.emailID;
	}

	public void setEmailID(String emailId) {
		this.emailID = emailId;
	}

	@Column(name = "phoneNumber", nullable = false)
	public int getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(int phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "firstName", nullable = false, length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "lastName", nullable = false, length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	
	public String getRole() {
		return role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@OneToOne(fetch = FetchType.EAGER, mappedBy = "user")
	public Buyer getBuyer() {
		return buyer;
	}

	public void setBuyer(Buyer buyer) {
		this.buyer = buyer;
	}

	@OneToOne(fetch = FetchType.EAGER, mappedBy = "user")
	public Seller getSeller() {
		return seller;
	}

	public void setSeller(Seller seller) {
		this.seller = seller;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
//	public Set<Seller> getSellers() {
//		return this.sellers;
//	}
//
//	public void setSellers(Set<Seller> sellers) {
//		this.sellers = sellers;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
//	public Set<Buyer> getBuyers() {
//		return this.buyers;
//	}
//
//	public void setBuyers(Set<Buyer> buyers) {
//		this.buyers = buyers;
//	}

	
}
